version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deployment
permissions:
  - object: scripts/
    mode: 777
    type:
      - directory
hooks:
  AfterInstall:
    - location: scripts/stop-containers.sh
      timeout: 300
    
  ApplicationStart:
    - location: scripts/start-containers.sh
      timeout: 300
     