version: 0.0
os: linux
files:
  - source: /deploy
    destination: /var/www/html
  - source: /backend
    destination: /var/www/backend
permissions:
  - object: scripts/
    mode: 777
    type:
      - directory
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
    
  ApplicationStart:
    - location: scripts/start-containers.sh
      timeout: 300
     