version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest  # Adjust to your required Node.js version
    commands:
      - echo "Installing dependencies"
      - git clone https://github.com/jenishk20/job-fit-ai-frontend frontend
      - git clone https://github.com/jenishk20/job-fit-ai-backend backend
  build:
    commands:
      - echo "Building frontend"
      - cd frontend && npm run build && cd ..
      - echo "Building backend"
      - cd backend && npm run start && cd ..
  post_build:
    commands:
      - echo "Copying build artifacts"
      - mkdir -p deploy
      - cp -R frontend/build/* deploy/
artifacts:
  files:
    - deploy/**/*
    - appspec.yml
    - scripts/**/*
    - docker-compose.yml
    - Dockerfile
