version: 0.2
phases:
  install:
    commands:
      - echo "the installation phase begins"
      - git clone https://github.com/jenishk20/job-fit-ai-frontend 
      - git clone https://github.com/jenishk20/job-fit-ai-backend
  pre_build:
    commands:
      - echo "the prebuild phase begins"
      - cd job-fit-ai-frontend
      - npm install
  build:
    commands:
      - echo "the build phase begins"
      - npm run build

  post_build:
    commands:
      - echo "the post build phase. navigating back to root path"
artifacts:
  files:
    - build/**/*
    - appspec.yml
    - server/**/*
    - nginx/*
    - scripts/*
    - docker-compose.yaml
    - Dockerfile